### ISSUE TITLE
Memory leak in automated mod.

### ISSUE THREAD

**Issue by ragzilla** [Cairath/tools-not-included#10]
**Describe the bug**
When running the Seed miner, memory is leaked (~200MB/seed mined).

**To Reproduce**
1. Put AutoSeedSharing.dll in mods folder
2. Start ONI
3. Watch memory util in task manager

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 10.0.17134 Build 17134
 - ONI Version Q2-311032

**Comment by Cairath** [comment]
There is a memory leak in the game's world gen -- sadly nothing I can do about it, we have to restart the game from time to time
