### ISSUE TITLE
Add Anti Entropy Thermo-Nullifier locations

### ISSUE THREAD

**Issue by remyroy** [Cairath/tools-not-included#11]
**Is your feature request related to a problem? Please describe.**
Knowning the location of Anti Entropy Thermo-Nullifiers would help select a better seed. My issue is having to check the map in debug mod for instance to see if the Anti Entropy Thermo-Nullifiers are close by water geysers.

**Describe the solution you'd like**
On the website, when you select a seed, in the word map view, it would be nice to see the Anti Entropy Thermo-Nullifier locations along side with the other geysers.

**Additional context**
See attached image for a visual.
![aetn-locations](https://user-images.githubusercontent.com/303593/53602762-b8452200-3b7d-11e9-82dc-9936149cc03d.png)

**Comment by nevir** [comment]
Looks like this one is resolved: https://toolsnotincluded.net/map-tools/map-browser/map/592
