### ISSUE TITLE
500 Error on the site, Seed Browser not live

### ISSUE THREAD

**Issue by MissScarIet** [Cairath/tools-not-included#15]
**Describe the bug**
Receiving a 500 error when trying to access the Seed Browser on the homepage and it says to contact the developer.

**To Reproduce**
1. Go to the homepage
2. See error

**Expected behavior**
I expected to browse seeds.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Steam in-game browser

**Comment by Cairath** [comment]
Thanks for reporting the crash, I've restarted the server

**Comment by MissScarIet** [comment]
Awesome! Thank you so much!

Warm Regards,
Jennifer Long 
www.jennlaurenlong.com ( https://share.polymail.io/v1/z/b/NWNhNGNkZTI3OThh/UBPF6QAcX4x1Iqqkzz2KswD-fA_xVySLPl0WdMq-8hSL4X3NWTHlxxB7fFhvmbsA4fBjlrZgrGYRGPvj93kf1qrgU-XGV7x2_3D2lM1o6PKY4-8hLvNDkECW_osJia6pZVrfN6QbKXjpBkMNBMHT7hqsG_90C1LvxKL1sMFdQfNDfb8gmdw0DkvtKzQhHpQqBrg8mZARoReH0YujGP-2ErVy50YnclB3p0EdG0OqUcA5lh3SANSeDhdHhIelB0pBpU2-u8W1o4aLgzbu-TXFpBiU4CXxICBpvlk6MUfZHWmsQKeeew== )
