### ISSUE TITLE
Sizing issue on mobile

### ISSUE THREAD

**Issue by Snackm1x** [Cairath/tools-not-included#16]
**Describe the bug**
The sides of your conatiner get cut off on mobile leaving some text missing.

**To Reproduce**
1. Go to website

**Expected behavior**
View all text in screen.

**Screenshots**
![Screenshot_20190430-145247](https://user-images.githubusercontent.com/6886612/56989535-4d51a080-6b58-11e9-8919-0bd167488b93.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3 XL
 - OS: Latest Android
 - Browser Chrome

**Comment by Cairath** [comment]
Hey @Snackm1x , due to some stressful stuff that's recently happened I'd like to turn this repo private and create a separate bugtracker. Would you be so kind to remove the fork? I would greatly appreciate it.
