### ISSUE TITLE
Search query to look up seeds by build version of game

### ISSUE THREAD

**Issue by loscil06** [Cairath/tools-not-included#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In the website you can search by many conditions, add a condition to look up specific game build versions.

**Describe alternatives you've considered**
Currently you have to look up seeds manually that are compatible with the current build version of the game you're playing

**Comment by Cairath** [comment]
That is because the server takes care of that - all shown seeds are compatible, world generation doesn't change every patch

**Comment by loscil06** [comment]
Thank you for the clarification. Great work, keep it up!
