### ISSUE TITLE
About new seed sharing

### ISSUE THREAD

**Issue by AbyssDrake** [Cairath/tools-not-included#23]
Hi,I am trying using your automatic seed sharing mod.However, I guess , it seems that mod doesn't  work due to new(test) version is revealed.

Will you update the mod so that I could use the mod to sharing seeds?

And thank you for the website, it helps so much!

**Comment by Cairath** [comment]
As the announcement on the website says, I'm working on a release version. There's many changes, the world gen isn't final, and I'm going on vacation -- so tldr it'll be ready when it's done :P
