### ISSUE TITLE
500 Error when visiting the site... Again

### ISSUE THREAD

**Issue by loscil06** [Cairath/tools-not-included#24]
**Describe the bug**
Description of this issue

**To Reproduce**
1. Go to main website
2. Click on nowhere
3. Scroll down to nowhere

**Expected behavior**
You should be able to see the website instead you see a duplicant with a cracked atmo suit

**Screenshots**
Think you've already seen it

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Server side issue

**Comment by Cairath** [comment]
it's back up! I'm working on release version and accidentally flipped the wrong kill switch this time :P Thanks for reporting

**Comment by loscil06** [comment]
Thank you
