### ISSUE TITLE
Malformed seed links on search page.

### ISSUE THREAD

**Issue by doguitar** [Cairath/tools-not-included#27]
After searching for seeds, links to the details page go to your 404 page. 

**To Reproduce**
1. Search for seed
2. Click on asteroid
3. Redirect URL is missing `map-tools` in the path

**Comment by Cairath** [comment]
I fixed that issue  yesterday, now going to the main page (https://toolsnotincluded.net) should redirect you  (with a path change) to /map-tools/map-browser -- please do a hard cache refresh (ctrl-f5) and see if it helps you

**Comment by doguitar** [comment]
Got it, fixed. Thanks.
