### ISSUE TITLE
map seed

### ISSUE THREAD

**Issue by Vardol** [Cairath/tools-not-included#28]
**Is your feature request related to a problem? Please describe.**
I was trying to use the generated coordinates, but the world never totally matches. I found that mapseed is probably wrong.
Finding a world with proper feats does not suffice, because locations like vascilator, entropy nullifier don't match.

**Describe the solution you'd like**
It is totally necessary to put a mapseed under a world map by whic it is generated.

**Alternate solution**
Maybe it is just me, and seed can be found somewhere. In that case it would be nice to put some sort of a manual.

**Comment by Cairath** [comment]
Hey,

this is re this issue: https://forums.kleientertainment.com/klei-bug-tracker/oni/asteroid-choice-screen-the-game-doesnt-react-correctly-to-player-input-r21089/ 

Hopefully it will get fixed soon, but in the meantime you have to go into 'Game Settings' when you are generating a new world and the two topmost options are the ones you want to change - asteroid type and seed number (seed number is the number part of the coordinate)
 I'll add a short description about it on the website when I push the next update

![](https://puu.sh/E02kZ/fa10c51ce0.png)

![](https://puu.sh/E02lq/631fb467df.png)

**Comment by studentmain** [comment]
> Hopefully it will get fixed soon

FYI, It's fixed now. My game version is LU-372041.
