### ISSUE TITLE
 Error 522 Connection timed out

### ISSUE THREAD

**Issue by loscil06** [Cairath/tools-not-included#31]
From Cloudfare: Ray ID: 50f1dadac97250d8 • 2019-08-31 20:46:37 UTC

**Comment by Cairath** [comment]
I know, it's the host's issue, nothing I can do, the manager is completely down right now x( They should fix it soon.

**Comment by Cairath** [comment]
it's back up now

**Comment by loscil06** [comment]
Thanks a lot!
