### ISSUE TITLE
map browser redirects to error 500 - internal server error

### ISSUE THREAD

**Issue by edazpotato** [Cairath/tools-not-included#32]
**Describe the bug**
The Map browser page returns *error 500 - internal server error*. some of the other pages also randomly return the same error.

**To Reproduce**
1. Go to 'the seed browser page'
2. See error

**Expected behavior**
The seed browser should come up

**Desktop (please complete the following information):**
 - OS: Crome OS
 - Browser google chrome
 - Version idk

**Additional context**
N/A

**Comment by Cairath** [comment]
thanks, i've restarted the server
