### ISSUE TITLE
Lost Save Games after running auto sharing

### ISSUE THREAD

**Issue by EnduringVirus** [Cairath/tools-not-included#33]
**Describe the bug**
Ran the Auto-sharing mod for about 15 min. Afterwards I cannot access Save Game files. Even brand new games I create and save dont show up. Either the game says it crashed and lets me send an error report, or when I click load game the load window is blank.

**To Reproduce**
1. Run mod
2. Remove mod from local folder to start game normally
3. Click Load Game

**Expected behavior**
Expected to load any of my old saves

**Screenshots**
[]https://imgur.com/t699pvi
[]https://imgur.com/3kyEwfv

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version :77.0.3865.120 (chrome version)

**Smartphone (please complete the following information):**
 - Device: Samsung s7]
 - OS: Oreo 8.0
 - Browser Chrome
 - Version 77.0.3865.116

**Additional context**
Checked the directory to be sure, my save games are present. It seems the game fails to find them or something? I also tried verify integrity of files on steam and everything checks out. I also went as far as uninstalling and reinstalling ONI but it still doesnt work.

**Comment by Cairath** [comment]
It cannot be the mod's fault. Check your antivirus or onedrive, they sometimes might be blocking access to files. You can also delete `C:\Users\username\Documents\Klei\OxygenNotIncluded\kplayerprefs.yaml` , it's known to sometimes get corrupted and crash the game until deleted.
