### ISSUE TITLE
www.toolsnotincluded.net shows an error message

### ISSUE THREAD

**Issue by RobertRuehlmann** [Cairath/tools-not-included#34]
The www subdomain of toolsnotincluded.net currently shows an error message. The plain "toolsnotincluded.net" domain without "www." works.

The browser console shows missing CORS headers for api.toolsnotincluded.net as the reason that the access from the www subdomain fails:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.toolsnotincluded.net/api/asteroids. (Reason: CORS header ‘Access-Control-Allow-Origin’ 
> missing).

**Comment by Cairath** [comment]
Thanks! Forgot to add a redirect after migrating the servers.
