### ISSUE TITLE
Geyser buffer

### ISSUE THREAD

**Issue by EmiledeKoning** [Cairath/tools-not-included#35]
Hi Cairath,
First of all, thanks for the awsome tool you created!

While using the geyser details I always find myself calculating the amount of liquid/gas tanks needed to buffer the active time so i can maintain the average output throught the dormant period.

Would it be possible to have a "tanks required" field added to the geyser details?

Thanks in advance!

**Comment by BlackestChaos96** [comment]
That would be an interesting thought
