### ISSUE TITLE
World Trait Finder tool returns incorrect traits per seed

### ISSUE THREAD

**Issue by ronindesign** [Cairath/tools-not-included#37]
**Describe the bug**
When selecting traits in the World Trait Finder tool, the produced seed does not result in the selected traits when entered in-game.

**To Reproduce**
1. Go to World Trait Finder
2. Select any traits
3. Enter starting seed
4. Generate new seed
5. Open game, create new game, select astroid
6. Enter seed previously found on World Trait Finder
7. Game shows a different set of traits then were selected and shown on World Trait Finder

**Expected behavior**
World Trait Finder seeds traits should match same traits as in-game.

**Screenshots**
![image](https://user-images.githubusercontent.com/1414401/76294131-86c26480-626f-11ea-8f51-4725ab6ffc87.png)
![image](https://user-images.githubusercontent.com/1414401/76294182-9e99e880-626f-11ea-85a8-0f562c1f398f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Game Version: 

**Additional context**
I found a different world trait finder tool that seems to produce correct results, may be of use as reference:
https://mrgamesdev.itch.io/oni-world-trait-finder

**Comment by Cairath** [comment]
It's taken out of the main menu for a reason -- it's not been updated yet. Can't provide current ETA>

**Comment by ronindesign** [comment]
No worries! Look forward to the update, please feel free to close in the meantime if you see fit!

**Comment by Cairath** [comment]
_Fixed this a few weeks ago but forgot to close the issue. Closing now._

**Comment by ronindesign** [comment]
Last commit was:
> 795c6b2 on Aug 22, 2019

Am I missing something?

**Comment by Cairath** [comment]
This repository is an issue-tracker only - actual source code is in another repository.
