### ISSUE TITLE
WorldMap Not Loading

### ISSUE THREAD

**Issue by KarliahCoyote** [Cairath/tools-not-included#38]
When a seed is selected, and I try to view the WorldMap, the image is there for less than a second, then is gone.

This is happening on my iPhone 7 & MacBook Air, both running most current iOS

**Comment by Cairath** [comment]
Hey, unfortunately I do not own any apple devices so I can't really check errors on Safari (unless you are using a different browser?) If it is Safari, please enter the developer console and see if there is anything in the log that would be of help.

**Comment by KarliahCoyote** [comment]
I don't know how to do any of that type of stuff. It just said to go here to report issues. Sorry.

**Comment by bpaul121** [comment]
I'm having this problem as well, I use chrome on a Mac. the page is not loading and after a few tries i got this message: 

Error 525 Ray ID: 5ac1f1975d31efc4 • 2020-07-01 17:45:57 UTC
SSL handshake failed
Cloudflare is unable to establish an SSL connection to the origin server
