### ISSUE TITLE
Manual Upload Mod - Crash when pressing the "Upload Seed" button 

### ISSUE THREAD

**Issue by Lee-Myhre** [Cairath/tools-not-included#39]
As of the past week, I have been unable to manually upload seeds using the manual upload mod.

1. Create a new game, select duplicants, and see the intro screen.
2. let the game unpause and play out for a second.
3. Click the "Upload Seed" button.

Crashes immediately, with the following error:
KButtonMenu+<>c__DisplayClass11_1.<RefreshButtons>b__1 () (at <a8d8cafbcd164cda9f477d36796bfc75>:0)
KButton.SignalClick (KKeyCode btn) (at <1dcc11867b524f7cb2488468843e982e>:0)
KButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <1dcc11867b524f7cb2488468843e982e>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <cfe2f64a3dc9415eb325f322bb4ecd6a>:0)
UnityEngine.EventSystems.EventSystem:Update()

 - OS: Windows
 - Browser: This is about the mod in ONI client, but if default browser affects the manual mod, I have switched my default over to New Microsoft Edge
 - ONI Version: Automation Update, patch 420700
- Upload Mod: Manual, Version 2 (via Steam Workshop)
- Additional mods: I play with only one other mod, Show Building Ranges (via Steam Workshop) but I have tested without and ruled out interference from that mod

**Comment by Cairath** [comment]
Recent update broke something, I'll try to look at it this week

**Comment by Cairath** [comment]
Version 4 has been pushed to steam and is also available on directly
https://static.toolsnotincluded.net/AutoMapSharing.zip
https://static.toolsnotincluded.net/MapSharing.zip
