### ISSUE TITLE
是否工具的间歇泉详情中“活跃期”“喷发期”的中文翻译 搞反了？Is the Chinese translation of "active period" and "eruption period" in the geyser details reversed?

### ISSUE THREAD

**Issue by Ventulus-lab** [Cairath/tools-not-included#42]
产量：6.38 kg/s 温度：110°C

【活跃期：362s / 854s】

【喷发期：76.5 周期 / 152.0 周期】

平均产量：1.36 kg/s

因为在跟这个网站https://oni-assistant.com/tools/geysercalculator  对比的时候，发现对不上，我特意去查了游戏内的翻译。
I went to check the official translation of the game：

msgctxt "STRINGS.UI.BUILDINGEFFECTS.GEYSER_PERIOD"
msgid "Eruption Period: {0} every {1}"
msgstr "喷发期：每{1}内喷发{0}"

msgctxt "STRINGS.UI.BUILDINGEFFECTS.GEYSER_YEAR_PERIOD"
msgid "Active Period: {0} every {1}"
msgstr "活跃期：每{1}内活跃{0}"

所以短的每多少秒是【Eruption Period喷发期】for seconds
长的多少个喷发循环活动后休眠多少个活动时间的，是【Active Period活跃期】for cycles

另外，除了（喷发）产量、(总活跃循环)平均产量，希望像上面网站一样，添加一个中间的 "活动时平均喷发循环产量"，因为往往用来蒸汽发电的热量保存不了太久。
In addition, in addition to the (Erupting) yield, (total Activity Cycle) average yield, it is hoped that, like the above website, add an intermediate "activity-time average eruption cycle yield", because often used for steam power generation heat can not be preserved for long.

**Comment by Cairath** [comment]
I do not own ONI-assistant, this is [Tools Not Included](https://toolsnotincluded.net)  issue tracker

**Comment by Ventulus-lab** [comment]
I mean, I compared the two sites and found that there was a problem with geyser details on Tools Not Included   map-tools!

**Comment by Ventulus-lab** [comment]
> I do not own ONI-assistant, this is [Tools Not Included](https://toolsnotincluded.net) issue tracker

I mean, I compared the two sites and found that there was a problem with geyser details on  Tools Not Included map-tools!

**Comment by Ventulus-lab** [comment]
![c](https://user-images.githubusercontent.com/76762951/104071006-23b0ae00-5243-11eb-8a61-ac9519e79c09.PNG)

**Comment by Cairath** [comment]
TNI does not have an official chinese translation - are you translating through google translate? Or using the chinese version via another URL?
![image](https://user-images.githubusercontent.com/10224213/104071187-ed563d00-5208-11eb-9ffd-8de94977fb9c.png)

The chinese version of the website, available at a different URL, is not ran by me. Someone stole the website and is running it against my permission. I am willing to add official translation but I don't have anyone to translate the website for me.

**Comment by Ventulus-lab** [comment]
Oh...I dont know who made the chinese translation  TNI website
https://onimap.upyoucan.com/about
The contact information of the above website is yours and does not leave the translator's contact information, so I thought it was your official chinese version of the website
@Cairath

**Comment by Cairath** [comment]
I would have added the translation to the website, but the person proceeded to keep breaching security instead of contacting me, so no clue. Nothing I can do about that one. I am hoping that someone Chinese will actually want to provide translation when I update to DLC.
