### ISSUE TITLE
Seed-World Map Inadequacies

### ISSUE THREAD

**Issue by alank2004** [Cairath/tools-not-included#44]
I suspect that there is something wrong with the program as I tried two seeds, 
SNDST-A-1437350708-0 and SNDST-A-527639751-0
and the world map that is generated is different from the one that I find myself in in game.

For instance with seed SNDST-A-527639751-0:
The expected chunk of the world that I am interested in should look like this:
![image](https://user-images.githubusercontent.com/56356389/127937406-c5420b3c-bf4b-4afc-a367-d72ffe924edb.png)
butr instead I find it looking like that:
![Screenshot 2021-08-02 185219](https://user-images.githubusercontent.com/56356389/127937338-28fcb685-fb00-4501-a894-410420738437.png)
Notably, there is no neural vaccinator or natural gas geiser on the border of the biomes.
I am running Windows 10 on my machine and as for the game, I am not running any mods nor am I running Spaced Out, which I don't think affects world spawn. The newest update did say that the developers "[are] continuing to refine worldgen tuning" and I suspect it has something to do with that.

**Comment by thure** [comment]
+1

New ONI maps no longer seem to match the ones in Tools Not Included…

**Comment by FredyReady** [comment]
+1

World upon seed generation seems to be changed. While the traits like "Geoactive, metal rich, etc..." seems to be same in ONI and TNI. The map itself is completely different. Did the world generation engine change again? Would be upsetting...

**Comment by BreakEnder233** [comment]
Hello there, just meet same problems and I suppose the world gen system actually changed... Hope it can be fixed soon.
And does it mean that the whole database would work no longer? So sad...

**Comment by Cairath** [comment]
Hey. As the site says, the current game version is not compatible with TNI. If you want to use old maps from TNI, you need to opt in to ver 496300 via steam betas, generate the map, then switch back to the current version. 

The database will be entirely wiped afterwards, as there is no way to  update/fix the maps after the worldgen has changed.

I've started working on DLC updates for TNI, but it's a lot of work and my time is currently very limited, so no idea how long it'll take.

**Comment by FredyReady** [comment]
Hi, thanks for the update, appreciate your work :)
