### ISSUE TITLE
toolsnotincluded.net is currently down

### ISSUE THREAD

**Issue by NicolasDer** [Cairath/tools-not-included#47]
toolsnotincluded.net is currently down

tested from different locations:
 - europe
 - america
 - asia

**Comment by Cairath** [comment]
Thanks for the report, but the site is down for extended maintenance until it's ready for the DLC!

**Comment by smkent** [comment]
@Cairath The world features and starmap searches were still very useful even though the world generation has changed in the base game. Is there any chance these features will be made available again? Alternatively, would you have any interest in publishing the source code for these former tools?

Thanks for all the work you've done to make toolsnotincluded.net great!
