### ISSUE TITLE
Automated mod ERROR 404

### ISSUE THREAD

**Issue by Kalinox** [Cairath/tools-not-included#48]
Hello,

i want to download the mod to contribute map generator at this link "https://static.toolsnotincluded.net/AutoMapSharing.zip"
But there are no file,  "404 NOT FOUND"

regards,

Kalinox

**Comment by Cairath** [comment]
Soon! Working on some last-minute fixes. Not officially released yet :P

**Comment by Cairath** [comment]
It's available now, but let's call it a public beta ;)
