### ISSUE TITLE
JSON requests

### ISSUE THREAD

**Issue by Hexicube** [Cairath/tools-not-included#5]
I have my own tool for keeping track of geysers, and I'd like to add a way to give it URLs from your site and have it load up the geysers from there and list them. JSON data would obviously be preferable for this.

**Comment by shanemadden** [comment]
I'd love to see your geyser calculator integrated with this tool, if you're interested in giving your permission to port the code and Cairath agrees - the percentile rating for a geyser could be displayed in the seed search interface as a 1-to-5-star rating for each geyser, and geyser filters in the seed search could potentially select geysers of only a certain rating (eg 'I want a seed with a 80-to-100th percentile Chlorine geyser').

**Comment by Hexicube** [comment]
https://github.com/Hexicube/Hexicube.github.io - Consider it under CC 3.0 BY-NC-SA.

The percentile math is inside the [calcRoll](https://github.com/Hexicube/Hexicube.github.io/blob/master/compute.js#L190) function, and comes from decompiled code. I'd suggest not doing equal-size blocks though, the last few percentiles have a large result range. Top and bottom 5% should be 1 and 5 IMO.

I think the best approach for your end to do the implementation would be to make use of that formula, as well as the creation of a link to mine. You can pass data into the URL, and I've specifically chosen delimiting characters to avoid running into encoded characters (i.e. %20 for space) so you don't need to worry about that. [Here](https://hexicube.github.io/volcano.html?data=SteamCold~2548.5~378~637~73.1~137_VolcBig~215900~70~8822~~_) is an example URL.

**Comment by Hexicube** [comment]
Poked around for a bit, found the JSON request route.

For others: https://api.toolsnotincluded.net/api/seeds/<seed>/<ver>

**Comment by Cairath** [comment]
Okay so CORS is there for a reason and blatantly getting around it when you see an error about lack of access from your domain (as you even noted in your code) and you don't get a response immediately is definitely not OK. 

I pay for the hosting and I don't have unlimited bandwidth, and I'm not fine with hooking up to the API **without permission** like that.


As for the actual functionality... percentile is on my todo list among many others, albeit not top priority as of now
