### ISSUE TITLE
All results are shown instead of none, if nothing was found

### ISSUE THREAD

**Issue by kingrodriguez** [Cairath/tools-not-included#50]
**Describe the bug**

I tried multiple different queries.
If matching seeds are found, all works fine.
If only one rule is in place (e.g. `more than 20 natural gas geysers`) but there are (obviously) no results, it shows that and it is fine.
If more than one rule is in place  (e.g. `more than 20 natural gas geysers` & `less than 5 natural gas geysers`), it shows all results instead of none.
This error also occurs with queries that make more sense.

**To Reproduce**
1. Go to `map browser`
2. select `aridio cluster`
3. add rule `more than 20 natural gas geysers on asteroid > aridio asteroid`
4. add rule `less than 5 natural gas geysers on asteroid > aridio asteroid`
5. see the wrong results

**Expected behavior**
It shows `no results`.

**Screenshots**
when i set up the query like this:
![image](https://user-images.githubusercontent.com/16023711/153171621-9a2f1f89-8541-4bf4-bd87-071fe8954e62.png)

the results are shown like this:
![image](https://user-images.githubusercontent.com/16023711/153171699-2772cf47-eb3f-4925-96bc-ddcc6b40cfe6.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Firefox 96.0.3

**Comment by Cairath** [comment]
You added "OR" rules. Works as expected.
