### ISSUE TITLE
save filters for seed finder

### ISSUE THREAD

**Issue by lizelive** [Cairath/tools-not-included#53]
**Is your feature request related to a problem? Please describe.**
im fusterating when i need to retype all my filters

**Describe the solution you'd like**
to be able to save filters to a url using https://www.npmjs.com/package/qs format

**Describe alternatives you've considered**
maybe a json format?

**Additional context**
love your work! also AGPL is a great!

**Comment by lizelive** [comment]
i know i can [use the api directly](https://api.toolsnotincluded.net/api/maps/filtered?page=1&pageSize=20&rules[0].value=1&rules[0].comparator=AtLeast&rules[0].type=Cluster&rules[0].groupId=0&rules[0].id=0&rules[0].itemType=Geyser&rules[0].item=liquid_co2&rules[1].value=1&rules[1].comparator=AtLeast&rules[1].type=Cluster&rules[1].groupId=1&rules[1].id=1&rules[1].itemType=Geyser&rules[1].item=slush_water&rules[2].value=1&rules[2].comparator=AtLeast&rules[2].type=Cluster&rules[2].groupId=2&rules[2].id=2&rules[2].itemType=Geyser&rules[2].item=methane&rules[3].value=1&rules[3].comparator=AtLeast&rules[3].type=Cluster&rules[3].groupId=3&rules[3].id=3&rules[3].itemType=Geyser&rules[3].item=hot_water&rules[4].value=1&rules[4].comparator=AtLeast&rules[4].type=Cluster&rules[4].groupId=4&rules[4].id=4&rules[4].itemType=Geyser&rules[4].item=salt_water&rules[5].value=1&rules[5].comparator=AtLeast&rules[5].type=Cluster&rules[5].groupId=5&rules[5].id=5&rules[5].itemType=Geyser&rules[5].item=slush_salt_water&rules[6].value=1&rules[6].comparator=AtLeast&rules[6].type=Cluster&rules[6].groupId=6&rules[6].id=6&rules[6].itemType=Geyser&rules[6].item=liquid_sulfur&rules[7].value=1&rules[7].comparator=AtLeast&rules[7].type=Cluster&rules[7].groupId=7&rules[7].id=7&rules[7].itemType=Geyser&rules[7].item=oil_reservoir&rules[8].value=1&rules[8].comparator=AtLeast&rules[8].type=Cluster&rules[8].groupId=8&rules[8].id=8&rules[8].itemType=Geyser&rules[8].item=oil_drip&rules[9].value=1&rules[9].comparator=AtLeast&rules[9].type=Cluster&rules[9].groupId=9&rules[9].id=9&rules[9].itemType=Geyser&rules[9].item=big_volcano&rules[10].value=1&rules[10].comparator=AtLeast&rules[10].type=Cluster&rules[10].groupId=10&rules[10].id=10&rules[10].itemType=Geyser&rules[10].item=small_volcano&rules[11].value=1&rules[11].comparator=AtLeast&rules[11].type=Cluster&rules[11].groupId=11&rules[11].id=11&rules[11].itemType=Geyser&rules[11].item=molten_copper&rules[12].value=1&rules[12].comparator=AtLeast&rules[12].type=Cluster&rules[12].groupId=12&rules[12].id=12&rules[12].itemType=Geyser&rules[12].item=molten_gold&rules[13].value=1&rules[13].comparator=AtLeast&rules[13].type=Cluster&rules[13].groupId=13&rules[13].id=13&rules[13].itemType=Geyser&rules[13].item=molten_iron&rules[14].value=1&rules[14].comparator=AtLeast&rules[14].type=Cluster&rules[14].groupId=14&rules[14].id=14&rules[14].itemType=Geyser&rules[14].item=molten_aluminum&rules[15].value=1&rules[15].comparator=AtLeast&rules[15].type=Cluster&rules[15].groupId=15&rules[15].id=15&rules[15].itemType=Geyser&rules[15].item=molten_tungsten&rules[16].value=1&rules[16].comparator=AtLeast&rules[16].type=Cluster&rules[16].groupId=16&rules[16].id=16&rules[16].itemType=Geyser&rules[16].item=molten_niobium&rules[17].value=1&rules[17].comparator=AtLeast&rules[17].type=Cluster&rules[17].groupId=17&rules[17].id=17&rules[17].itemType=Geyser&rules[17].item=molten_cobalt&rules[18].value=1&rules[18].comparator=AtLeast&rules[18].type=Cluster&rules[18].groupId=18&rules[18].id=18&rules[18].itemType=Geyser&rules[18].item=chlorine_gas&rules[19].value=1&rules[19].comparator=AtLeast&rules[19].type=Cluster&rules[19].groupId=19&rules[19].id=19&rules[19].itemType=Geyser&rules[19].item=hot_co2&rules[20].value=1&rules[20].comparator=AtLeast&rules[20].type=Cluster&rules[20].groupId=20&rules[20].id=20&rules[20].itemType=Geyser&rules[20].item=steam&rules[21].value=1&rules[21].comparator=AtLeast&rules[21].type=Cluster&rules[21].groupId=21&rules[21].id=21&rules[21].itemType=Geyser&rules[21].item=hot_steam&rules[22].value=1&rules[22].comparator=AtLeast&rules[22].type=Cluster&rules[22].groupId=22&rules[22].id=22&rules[22].itemType=Geyser&rules[22].item=hot_hydrogen&rules[23].value=1&rules[23].comparator=AtLeast&rules[23].type=Cluster&rules[23].groupId=23&rules[23].id=23&rules[23].itemType=Geyser&rules[23].item=filthy_water&rules[24].value=1&rules[24].comparator=AtLeast&rules[24].type=Cluster&rules[24].groupId=24&rules[24].id=24&rules[24].itemType=Geyser&rules[24].item=hot_po2&rules[25].value=1&rules[25].comparator=AtLeast&rules[25].type=Cluster&rules[25].groupId=25&rules[25].id=25&rules[25].itemType=Geyser&rules[25].item=slimy_po2&expansion=SpacedOut) which seems to use qs format. expose that to us plebians user so we can share and use the ui. also if the page fails to return for any reason it resets your settings which sucks.

**Comment by lizelive** [comment]
that url is 'has all gysers' and was created via the ui - it times out 100% of the time

**Comment by Cairath** [comment]
Won't do. Had a save feature before, was barely used and only generated reports when i needed to change something and people's saved code was no longer valid.
