### ISSUE TITLE
Feature request - Filtering by biome type

### ISSUE THREAD

**Issue by HiddenKn** [Cairath/tools-not-included#7]
**Is your feature request related to a problem? Please describe.** 
I find it difficult to find seeds with large biomes of specific types.

**Describe the solution you'd like**
I think it would be helpful if either the API or the website contained a feature to specify you want the seed to have at least/at most 20% ice biome for example.

**Describe alternatives you've considered**
Filtering by certain blocks would be possible as well but seems less practical.

**Additional context**

**Comment by HiddenKn** [comment]
P.s. I would love a new invite URL for Discord, the invite URL in the Readme file does not work for me.

**Comment by Cairath** [comment]
Oops, fixed the discord links.

And I'll keep the above as a suggestion, thanks!
