### ISSUE TITLE
Mod counts 60 second timeout from world gen rather than map start

### ISSUE THREAD

**Issue by SquidPony** [Cairath/tools-not-included#8]
**Describe the bug**
If time is taken to mess about rerolling dupes at the beginning more than 60 seconds might pass before the actual game start has happened. In that case the "took too long" error shows up even though nothing in the world has actually started yet.

**To Reproduce**
1. Start new world
2. Wait on Dupe selection screen more than time limit
3. Continue to game
4. Attempt to upload seed

**Expected behavior**
Mod should start counting down from map start rather than dupe selection counting

**Additional context**
For all I know the world actually does start simulating during the dupe selection screen, in which case this mod is working as it should :)

**Comment by Cairath** [comment]
Hi,

sorry for the delay, totally forgot to respond. This is a tough choice, as the only times available for me are loading the world (so you could load a very old seed and it'd be freshly loaded) or natively game-calculated world played time, which unfortunately counts from the moment world is created -- so when the dupe selection starts. I'll think about increasing the timer, but no promises here -- as it is possible to generate the same seed and skip the dupe selection just for uploading purposes,

**Comment by SquidPony** [comment]
I've been following the "skip first and re-enter if it's good" process. Given the timing limitations, that process is probably good enough

Is there any way to check stocks? Such as if no building materials are available then it's likely nothing has happened yet?

**Comment by Cairath** [comment]
Yep -- they are checked, but with sandbox or debug you can do virtually anything without leaving a trace in the inventory
