### ISSUE TITLE
Automatic version crashes with game version Q2-309851

### ISSUE THREAD

**Issue by remyroy** [Cairath/tools-not-included#9]
**Describe the bug**
After installing the automatic version of the mod with game version *Q2-309851*, starting a new game shows a new world with the initial 3 dupes, but it immediately crashes after that.

**To Reproduce**
1. Make sure you are using game version *Q2-309851*
2. Install the automatic version of the mod following the procedure on https://toolsnotincluded.net/seeds/modinfo
3. Start the game
4. In the main menu, click new game
5. Observe the crash

**Expected behavior**
After step 4, it shouldn't crash

**Debug info**
debug.log shows

```
[0220/161555.031:ERROR:settings.cc(324)] Settings version is not 1
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The manual version of the mod seems to be working fine with *Q2-309851*.

**Comment by Cairath** [comment]
Thanks for the report! I've uploaded version 1.1 of the automated mod, you can get it in the same location as previously.

**Comment by remyroy** [comment]
I just tried downloading the automatic mod from https://toolsnotincluded.net/seeds/modinfo and ultimately from https://static.toolsnotincluded.net/mod/AutoSeedSharing.dll and it has the same hash as the previous version which was causing this issue. Did you update the binary there? If not, let me know where I can find it.

Thanks

**Comment by Cairath** [comment]
Yes, the binary has been updated. It was just a one line change, though not sure why hash wouldn't change.  The new filesize is 32KB vs 33.5KB for the old one.
